name: Build and Upload native binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  builder:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'macos-15', 'windows-latest']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      if: matrix.os == 'ubuntu-latest'
    - uses: oras-project/setup-oras@v1
    - run: oras version
    - name: Build
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          bash thirdparty/sourcekitten/build.sh
          bash packages/linux-arm64/build-linux-arm64.sh
          bash packages/linux-arm/build-linux-arm.sh
          bash packages/ppc64/build-ppc64.sh
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          powershell ./packages/windows-amd64/build-windows-amd64.ps1
          powershell ./packages/windows-arm64/build-windows-arm64.ps1
        else
          bash thirdparty/sourcekitten/build.sh
        fi
        ls -l thirdparty/sourcekitten/SourceKitten/.build/release
        echo $GITHUB_TOKEN | oras login ghcr.io -u $GITHUB_USERNAME --password-stdin
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload linux amd64
      run: |
        cd thirdparty/sourcekitten/SourceKitten/.build/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:linux-amd64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./sourcekitten:application/vnd.cyclonedx.plugins.layer.v1+tar \
          ./sourcekitten.sha256:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'ubuntu-latest'
    - name: Upload linux arm64
      run: |
        cd packages/linux-arm64/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:linux-arm64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./arm64-binary:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'ubuntu-latest'
    - name: Upload linux arm
      run: |
        cd packages/linux-arm/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:linux-arm \
          --artifact-type application/vnd.oras.config.v1+json \
          ./arm-binary:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'ubuntu-latest'
    - name: Upload darwin amd64
      run: |
        cd thirdparty/sourcekitten/SourceKitten/.build/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:darwin-amd64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./sourcekitten:application/vnd.cyclonedx.plugins.layer.v1+tar \
          ./sourcekitten.sha256:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'macos-13'
    - name: Upload darwin arm64
      run: |
        cd thirdparty/sourcekitten/SourceKitten/.build/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:darwin-arm64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./sourcekitten:application/vnd.cyclonedx.plugins.layer.v1+tar \
          ./sourcekitten.sha256:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'macos-15'
    - name: Upload windows amd64
      run: |
        cd packages/windows-amd64/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:windows-amd64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./windows-binary:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'windows-latest'
    - name: Upload windows arm64
      run: |
        cd packages/windows-arm64/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:windows-arm64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./windows-arm64-binary:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'windows-latest'
    - name: Upload ppc64
      run: |
        cd packages/ppc64/release/
        oras push ghcr.io/cyclonedx/cdxgen-plugins-bin:ppc64 \
          --artifact-type application/vnd.oras.config.v1+json \
          ./ppc64-binary:application/vnd.cyclonedx.plugins.layer.v1+tar
      if: matrix.os == 'ubuntu-latest'
